# Generated by Django 5.0.3 on 2024-06-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcontrol', '0005_alter_engagement_end_date_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementdetail',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
