# Generated by Django 5.0.3 on 2024-06-10 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcontrol', '0007_alter_engagementdetail_status_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='engagement',
        ),
        migrations.AddField(
            model_name='task',
            name='engagement_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskcontrol.engagementdetail'),
        ),
    ]
