# Generated by Django 5.0.3 on 2024-06-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcontrol', '0010_engagement_completed_at_engagement_completed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementdetail',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
