# Generated by Django 5.0.3 on 2024-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcontrol', '0011_alter_engagement_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementdetail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
