# Generated by Django 5.0.3 on 2024-06-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskcontrol', '0012_engagementdetail_notes_task_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagementdetail',
            old_name='notes',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='notes',
            new_name='comment',
        ),
    ]
