# Generated by Django 5.0.3 on 2024-06-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskcontrol', '0014_remove_task_engagement_detail_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementdetail',
            name='notification_day',
            field=models.SmallIntegerField(null=True),
        ),
    ]
