# Generated by Django 5.0.3 on 2024-06-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskcontrol', '0016_alter_engagementdetail_notification_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementdetail',
            name='notification_day',
        ),
    ]
